vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        property_images:
            uri_prefix: public/images/property_images
            upload_destination: '%kernel.project_dir%/public/images/property_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
