#home:
 #   path: /
  #  controller: App\Controller\HomeController::index

controllers:
    resource: ../src/Controller/
    type: attribute

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"